development:
  adapter: postgresql
  encoding: unicode
  database: zen_contact_development
  pool: 5
  host: localhost
  username: postgres
  password:


test: &test
  adapter: postgresql
  encoding: unicode
  database: zen_contact_test
  pool: 5
  host: localhost
  username: postgres
  password:
