# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3842ed246815fd0538215ed83af603d0c00b4acba8193c7e5ae46859d43cc99969ce2278982e7a422df4b4e6b3a5417dc74da88d370386504ce21296ffcdbdc

test:
  secret_key_base: b34f988357c6a09f54a266e81ecd5083327e5ae456e16f14c85ef96ed150df8e5e9186266344fbca040316906e2f29d22f620b897563afce49880ff2a59c72d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
